FROM        ubuntu:14.04

MAINTAINER  Biju Joseph

ENV DEBIAN_FRONTEND noninteractive

# INSTALL OS DEPENDENCIES
RUN         apt-get update; apt-get install -y software-properties-common zip
RUN         apt-get install -y unzip 
RUN         apt-get install -y vim 

